Feature/dayd 676
daydule/frontend pull request #29
Opened 2023-06-04 04:32 UTC by Mellbrother

# 事前確認

- [ ] PR 前に動作確認をしたか
- [ ] ビルドエラー/ESLint エラーは起きていないか
- [ ] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
- [ ] 機密情報を含んでいないか
- [ ] 最新の`develop`ブランチを反映しているか

# やったこと

# やらないこと

# 懸念点や注意点

# その他

2023-06-12 00:23 UTC, tom-takeru requested changes
レビューしたー

2023-06-12 00:23 UTC, tom-takeru commented on public/markdownContents/about.md
> +- 無料のホスティングサービスを利用しているため、DB のデータが 90 日で一度リセットされます。
もう90日のカウントダウン始まってて8月の中旬くらいには一回消えるんだった気がするから
「〜月〜日までのベータ版です」
の方が良いんじゃないかな？

2023-06-12 00:23 UTC, tom-takeru commented on public/favicons/site.webmanifest
> +}
このファイルってどんな意味なの？

2023-06-12 00:23 UTC, tom-takeru commented on public/favicons/browserconfig.xml
> +</browserconfig>
このファイルどんな意味？

2023-06-12 00:23 UTC, tom-takeru commented on src/components/organisms/MarkdownContentsComponent.tsx
> +};
<img width="1663" alt="image" src="https://github.com/daydule/frontend/assets/57748294/818927bd-af2c-4877-a5c5-5f9d2b03b55a">
最後の行がフッターで隠れてる

2023-06-12 00:23 UTC, tom-takeru commented on src/pages/about/index.tsx
> +export default AboutPage;
ログイン画面への動線ってある？
あるとしたら、わからなかったから目立つようにした方がいいかな

2023-06-14 11:00 UTC, Mellbrother commented on public/favicons/site.webmanifest
> +}
画像作成したときに自動で生成されたファイル
内容よくわからない。。

2023-06-14 11:01 UTC, Mellbrother commented on public/favicons/browserconfig.xml
> +</browserconfig>
画像作成したときに自動で生成されたファイル
内容よくわからない。。

2023-06-14 11:01 UTC, Mellbrother commented on public/markdownContents/about.md
> +- 無料のホスティングサービスを利用しているため、DB のデータが 90 日で一度リセットされます。
リセットされる旨追加する

2023-06-25 12:21 UTC, Mellbrother commented on src/pages/about/index.tsx
> +export default AboutPage;
ログイン画面用の動線を追加した　

2023-06-25 12:22 UTC, Mellbrother commented on src/components/organisms/MarkdownContentsComponent.tsx
> +};
暫定対応で---を下にいれた

2023-06-25 23:35 UTC, tom-takeru approved these changes
🦅

2023-06-25 23:36 UTC, merged