DAYD-676 [FE]ログイン時にEntreを押すことでSubmitできるよう修正
daydule/frontend pull request #33
Opened 2023-06-14 11:48 UTC by kzk27

# 事前確認

- [ ] PR 前に動作確認をしたか
- [ ] ビルドエラー/ESLint エラーは起きていないか
- [ ] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
- [ ] 機密情報を含んでいないか
- [ ] 最新の`develop`ブランチを反映しているか

# やったこと
- ログイン画面については、EnterでSubmitできるよう実装

# やらないこと
- ログイン画面以外でSubmitを行う箇所については対象外（このPRがマージ後に対応）

# 懸念点や注意点

# その他

2023-06-14 11:58 UTC, tom-takeru commented on src/components/atoms/InputWithIconComponent.tsx
> +  handleClickLogin: () => void;
- [ ] handleClickLoginをhandleSubmitに変更
- [ ] SimpleInputComponentにもこの変更を適用

2023-06-14 12:03 UTC, tom-takeru requested changes

2023-06-14 12:03 UTC, tom-takeru commented on src/components/atoms/InputWithIconComponent.tsx
> +  handleClickLogin: () => void;
- [x] handleClickLoginをhandleSubmitに変更
- [x] SignupComponentでも適用されるように変更

2023-06-17 21:21 UTC, tom-takeru requested changes
コメントしました！
最初のレビューで気付かなくてごめんなさい 🙇

2023-06-17 21:21 UTC, tom-takeru commented on src/components/organisms/LoginComponent.tsx
>                placeholder='メールアドレス'
ごめんなさい、最初に気づければよかったんですがこの原因は↓な気がしてきました、、、。
https://stackoverflow.com/questions/33211672/how-to-submit-a-form-using-enter-key-in-react-js

↑の記事の内容としては「以下のような実装にしよう」ということです。

```
const onFormSubmit = e => {
  e.preventDefault();
  // send state to server with e.g. `window.fetch`
}

...

<form onSubmit={onFormSubmit}>
  ...
  <button type="submit">Submit</button>
</form>
```

最初のレビューで気付かなくて、ごめんなさい 🙇 
RegisterPlanComponent.tsxなどでは、追加実装しなくてもインプットボックスでエンターを押したらSubmitされていることから気づきました。RegisterPlanComponent.tsxの実装を参考にしてみてください。

2023-06-20 13:53 UTC, kzk27 commented on src/components/organisms/LoginComponent.tsx
>                placeholder='メールアドレス'
指摘いただいた内容を参考に実装しましたのでクローズします！

2023-06-21 10:13 UTC, tom-takeru commented on src/components/atoms/InputWithIconComponent.tsx
> +import React, { ReactNode } from 'react';
これは不要になったやつですかね？

2023-06-22 12:21 UTC, atoook submitted a review, later dismissed
動作確認しました。
importの指摘点以外は問題ないと思いますので承認します。
※プルリクのタイトルがDYD-676となっていますが、767が正しいチケットNOかと思いますのでそちらだけ変更お願いします。

2023-06-25 23:33 UTC, tom-takeru approved these changes
🍔

2023-06-29 12:08 UTC, atoook approved these changes
LGTM!

2023-06-29 12:08 UTC, merged