DAYD-856 lintの設定変更及びエラー解消
daydule/frontend pull request #48
Opened 2023-08-12 17:37 UTC by kzk27

# 事前確認

-   [x] PR前に動作確認をしたか
-   [x] ビルドエラー/ESLintエラーは起きていないか
-   [x] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか

~-   [ ] 単体テストが全てOKになっているか~（現状はフロントエンドの単体テストを実行できていないため）

-   [x] 機密情報を含んでいないか
-   [x] 最新の`develop`ブランチを反映しているか

# レビュワーによる動作確認

- [ ] @tom-takeru 
- [ ] @atoook 

# やったこと
- lint周りでエラーが出ていたので解消しました
  - 原因：パッケージのインストール不足
- lint:fix では修正されないlintエラーを手動で修正
  - 手動で修正した箇所についてはコメントにて記載しております

# やらないこと
特になし

# 懸念点や注意点
特になし

# その他
特になし

2023-08-12 17:57 UTC, kzk27 reviewed
lint:fixでは修正されなかった部分を手動で修正しましたので、ご確認お願いします🙇

2023-08-12 17:57 UTC, kzk27 commented on src/components/molecules/RegisterPlanModalComponent.tsx
>            <ButtonComponent type='submit' children='登録' />
text-mdはTailwindに存在しないクラスなので削除

2023-08-12 17:57 UTC, kzk27 commented on src/components/organisms/ScheduleComponent.tsx
>                style={{ top: 'calc(' + Math.round(i * oneMinuteHeightPercent * 60 * 100) / 100 + '% + 1rem)' }}
border-500-grayはTailwindに存在しないクラスなので削除

2023-08-12 17:57 UTC, kzk27 commented on src/pages/main/index.tsx
>            <RegisterPlanComponent />
誤字修正：h-hull → h-full

2023-08-12 17:57 UTC, kzk27 commented on src/components/organisms/TodoListComponent.tsx
>  import { IconContext } from 'react-icons';
DropResultは型定義のインポートなのでimport方法を分けて記述

2023-08-12 17:57 UTC, kzk27 commented on src/components/organisms/TodoListComponent.tsx
> +      <div className='absolute left-3 top-3 rounded-lg bg-white px-2 text-xl'>TODO一覧</div>
bg-opacity-50という余分なopacityが含まれていたので削除しました（クラスを削除しても変化がないことは確認済み）

2023-08-12 17:57 UTC, kzk27 commented on src/components/organisms/TodoListComponent.tsx
>    }, [scheduleReadResult]);
依存配列に「todoOrder」を追加しないとlintエラー（eslint-disable-next-line react-hooks/exhaustive-deps）が発生してしまうが、追加すると無限リロードが発生してしまうためlintを無効化

2023-08-12 17:57 UTC, kzk27 commented on src/components/atoms/SimpleInputComponent.tsx
>  export const SimpleInputComponent = forwardRef((props: Props, ref: React.Ref<HTMLInputElement>) => {
関数に名前をつけないとlintエラー（eslint-disable-next-line react/display-name）が発生してしまうが、forwardRefを利用しているため関数名をつけれないのでlintを無効化

2023-08-12 17:57 UTC, kzk27 commented on src/components/organisms/HeaderComponent.tsx
>          </IconContext.Provider>
alt属性を追加

2023-08-12 17:57 UTC, kzk27 commented on .eslintrc.json
> +    "react/react-in-jsx-scope": "off",
Reactのインポートが必須となるルールだが、React v17以降は記述不要のためオフに設定

2023-08-12 17:57 UTC, kzk27 commented on .eslintrc.json
> +    "react/no-children-prop": "off",
propsでchildrenを利用を禁止するルールだが、本プロジェクトでは利用されているためオフに設定

2023-08-12 17:57 UTC, kzk27 commented on .eslintrc.json
> +    "react/prop-types": "off",
関数コンポーネントのpropsの型にジェネリクスを利用しようとするとエラーが出るためルールをオフに設定

2023-08-12 17:57 UTC, kzk27 commented on .eslintrc.json
> +    "react-hooks/rules-of-hooks": "off",
条件分岐による早期リターン後にuseStateを定義するとエラーが発生するのでルールをオフに設定

2023-08-12 17:57 UTC, kzk27 commented on .eslintrc.json
> +    "@next/next/no-img-element": "off"
imgタグではなく、Next.jsのImageを利用しないといけないルールだが、Imageはwithを指定しないとエラーが発生する仕様のためimgタグで対応できるようルールをオフに設定

2023-08-13 00:15 UTC, tom-takeru requested changes
色々と技術的な負債解消していただいて、ありがとうございます :bow:
いくつかコメントを書きました。

ちなみに、今後はこういうことが起きてしまわないようにlintチェックなどのCI/CDの整備を川本さんにやってもらう予定です！

2023-08-13 00:15 UTC, tom-takeru commented on .eslintrc.json
> +    "react/no-children-prop": "off",
これって後々`error`とかにできるようにリファクタリングした方が良いんですかね？
森さん的にはどう思いますか？

2023-08-13 00:15 UTC, tom-takeru commented on .eslintrc.json
> +    "react-hooks/rules-of-hooks": "off",
これって後々`error`とかにできるようにリファクタリングした方が良いんですかね？②

2023-08-13 00:15 UTC, tom-takeru commented on src/components/atoms/SimpleInputComponent.tsx
>  export const SimpleInputComponent = forwardRef((props: Props, ref: React.Ref<HTMLInputElement>) => {
一応↓みたいにすると関数名はつけれるみたいです！
```
export const SimpleInputComponent = forwardRef(function x(props: Props, ref: React.Ref<HTMLInputElement>) {
```
ただつける名前も思いつかないので、現対応の「コメントで無効化」で良いと思います！

2023-08-13 00:15 UTC, tom-takeru commented on package.json
> +    "eslint-plugin-tailwindcss": "^3.13.0",
興味本位なので、何かご存知だったらで大丈夫なんですが、
今回いきなりVercelでビルドできなくなってしまったのって、なんでだかわかったりしますか？
Vercelがlintチェックもしてくれるようになったんですかね？

2023-08-13 00:15 UTC, tom-takeru commented on src/components/atoms/SimpleInputComponent.tsx
このコンポーネントのpropsが川本さんのデザイン調整プルリクで変わっています。
ですが、リベース？によって呼び出し元では元のままになってしまっているようです。

<img width="1680" alt="image" src="https://github.com/daydule/frontend/assets/57748294/b843fdef-3215-4827-b573-58ab23d5a022">

2023-08-13 00:15 UTC, tom-takeru commented on src/components/organisms/TodoListComponent.tsx
>    }, [scheduleReadResult]);
```suggestion
            .filter((id) => id !== null)
        : [],
    );
  }, [scheduleReadResult]);
```

↑これでも良いですか？
useEffect内でtodoOrderを使っている意味はあまりなさそうなので！
お手数ですが、お願いします :bow:

2023-08-13 11:33 UTC, kzk27 commented on package.json
> +    "eslint-plugin-tailwindcss": "^3.13.0",
その辺はよくわからないですね🤔 
Vercel周りの知識があまりないので原因については自分からはなんとも言えないといった感じです。。。

2023-08-16 11:42 UTC, Mellbrother commented on .eslintrc.json
> +    "react/no-children-prop": "off",
リファクタする

2023-08-16 11:42 UTC, Mellbrother commented on .eslintrc.json
> +    "react-hooks/rules-of-hooks": "off",
検討するチケットを別途起票する

2023-08-16 11:45 UTC, tom-takeru approved these changes
🍎

2023-08-16 11:45 UTC, atoook approved these changes
LGTM!

2023-08-16 11:46 UTC, merged