DYD-950 CheckBoxComponentにpropsを追加しでラベルの表示位置を指定できるよう修正&Storybookの追加
daydule/frontend pull request #71
Opened 2023-11-22 15:50 UTC by atoook

# 事前確認

- [ ] PR 前に動作確認をしたか
- [ ] ビルドエラー/ESLint エラーは起きていないか
- [ ] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか

~- [ ] 単体テストが全て OK になっているか~（現状はフロントエンドの単体テストを実行できていないため）

- [ ] 機密情報を含んでいないか
- [ ] 最新の`develop`ブランチを反映しているか

# レビュー優先度（どれか一つ）

- [ ] すぐ見てもらいたい
- [ ] 3 日くらいで見てもらいたい
- [ ] 7 日くらいで見てもらいたい

# レビューの度合い

- [ ] コードをぱっと確認してもらいたい
- [ ] コードをぱっと確認 & 動作確認してもらいたい
- [ ] コードをしっかり確認 & 動作確認してもらいたい

# レビュワーによる動作確認

- [ ] @tom-takeru 
- [ ] @Mellbrother 
- [ ] @kzk27 

# やったこと
繰り返し予定の画面を作成する過程で、チェックボックスコンポーネントのラベル位置を変えられるようにした方が良さそうだと感じ修正しました。
繰り返し予定画面の作成タスクは次以降に落ちたので、ひとまずこの修正だけでも反映したいです。

# やらないこと
繰り返し予定画面の作成

特になし

# 懸念点や注意点

特になし

# その他

特になし

2023-11-24 23:37 UTC, tom-takeru requested changes
コメントしました！
確認をお願いします🙏

2023-11-24 23:37 UTC, tom-takeru commented on src/components/common/leaf/CheckBoxComponent.tsx
> +  key?: number;
この　key　Props　って必要ですか？
Reactでリストでレンダリングする際に必要になるものだと思うので、リストかどうか？は呼び出しもと次第であり、必要ないように思いました　🐊
Storybook　の　GroupedCheckBox　のように、親要素の　div　に　key　を持たせれば、このコンポーネントには　key　Props　は持たせなくてもエラーは出ないはずです！

2023-11-24 23:37 UTC, tom-takeru commented on src/components/common/leaf/CheckBoxComponent.stories.tsx
> +export const BottomCheckBox: Story = {
<img width="96" alt="image" src="https://github.com/daydule/frontend/assets/57748294/dac0172a-4c08-4f51-aeb5-69fd39fa5593">

このストーリーを見て思ったのですが、
- 縦書き
  - もしくは
- 文章の中央あたりの位置にチェックボックス
が良いと思ったのですがどうでしょうか？

topに関しても同様です。

2023-11-25 00:17 UTC, tom-takeru commented on src/components/common/leaf/CheckBoxComponent.tsx
> +   * チェックボックスの初期値です。
```suggestion
   * チェックボックスの状態を表す値です。
```
↑するのはどうでしょうか？
動的に変わるものなので意味合いは初期値だけではないと思いました🐊

OKなら`Commit suggestion`ボタンを押して変更を適用してしまってください。

2023-11-27 14:45 UTC, Mellbrother commented on src/components/common/leaf/CheckBoxComponent.tsx
> +  /**
ここですが、変数名から推測できる情報とコメントから得られる情報にほとんど差がないので、コメント不要かと思います（titleという変数名からタイトルで使うことは容易に推測できる）

2023-11-27 14:45 UTC, Mellbrother commented on src/components/common/leaf/CheckBoxComponent.tsx
> +  /**
ここですが、変数名から推測できる情報とコメントから得られる情報にほとんど差がないので、コメント不要かと思います（labelLocationという変数名からラベルの表示位置を設定することは容易に推測できる）

2023-11-27 14:45 UTC, Mellbrother commented on src/components/common/leaf/CheckBoxComponent.tsx
> +   * チェックボックスの初期値です。
初期値なのであれば、変数名はdefaultValueの方が良いと思います
値（初期値だけではない）なのであれば、コメントは不要かと思います（冗長なため）

2023-12-02 00:28 UTC, atoook commented on src/components/common/leaf/CheckBoxComponent.tsx
> +  key?: number;
不要なkey Propsを削除しました。

2023-12-02 00:29 UTC, atoook commented on src/components/common/leaf/CheckBoxComponent.stories.tsx
> +export const BottomCheckBox: Story = {
チェックボックスに対して中央揃えになるよう修正しました。

2023-12-02 00:29 UTC, atoook commented on src/components/common/leaf/CheckBoxComponent.tsx
> +   * チェックボックスの初期値です。
不要なコメントを削除しました。

2023-12-02 00:30 UTC, atoook commented on src/components/common/leaf/CheckBoxComponent.tsx
> +  /**
不要なコメントを削除しました。

2023-12-02 00:30 UTC, atoook commented on src/components/common/leaf/CheckBoxComponent.tsx
> +  /**
不要なコメントを削除しました。

2023-12-02 00:48 UTC, atoook commented on src/components/common/leaf/CheckBoxComponent.tsx
> +      extraLabelClass = 'mb-2 ml-1 mr-1';
(bottomも同様)
label要素の幅がinput要素の幅より小さい時に、input要素がlabel要素に対して左寄せにならないように'ml-1 mr-1'を追加しました。
※以下のストーリーブック参照
https://www.chromatic.com/test?appId=6529f98815fbf0c40d4c01ba&id=656a7a329fbde913e9a2928e

ローカルで半角英数の場合も左寄せにならないことは確認しました。

2023-12-02 03:03 UTC, tom-takeru reviewed
書き方のところだけコメントしました！
最初のレビューで気づかなくてごめんなさい🙏

2023-12-02 03:03 UTC, tom-takeru commented on src/components/common/leaf/CheckBoxComponent.tsx
> +    <div className={`${parentClass}`}>
```suggestion
    <div className={parentClass}>
```
これでも良いはず！

2023-12-02 03:03 UTC, tom-takeru commented on src/components/common/leaf/CheckBoxComponent.tsx
> +          `${extraInputClass}`,
```suggestion
          extraInputClass,
```
これでも良いはず2

2023-12-02 03:03 UTC, tom-takeru commented on src/components/common/leaf/CheckBoxComponent.tsx
> +          className={twMerge('block text-sm font-medium text-gray-900', `${extraLabelClass}`)}
```suggestion
          className={twMerge('block text-sm font-medium text-gray-900', extraLabelClass)}
```
これでも良いはず3
おなじようなところがあれば、そこもお願いします🙏

2023-12-02 03:11 UTC, atoook commented on src/components/common/leaf/CheckBoxComponent.tsx
> +    <div className={`${parentClass}`}>
対応しました！

2023-12-02 03:11 UTC, atoook commented on src/components/common/leaf/CheckBoxComponent.tsx
> +          `${extraInputClass}`,
対応しました！

2023-12-02 03:11 UTC, atoook commented on src/components/common/leaf/CheckBoxComponent.tsx
> +          className={twMerge('block text-sm font-medium text-gray-900', `${extraLabelClass}`)}
対応しました！

2023-12-03 05:18 UTC, Mellbrother approved these changes
LGTM

2023-12-03 06:03 UTC, tom-takeru approved these changes
LGTM 📦

2023-12-03 06:03 UTC, tom-takeru commented on src/components/common/leaf/CheckBoxComponent.tsx
> +      extraLabelClass = 'mb-2 ml-1 mr-1';
(ただのメモ)
flexboxでも対応できる気がしていました！
[参考](https://coliss.com/articles/build-websites/operation/css/css3-flexbox-properties-by-scotch.html)

2023-12-03 06:36 UTC, merged